framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: quiz_app

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        app: cache.adapter.filesystem
        
        # Redis for production (uncomment when you have Redis)
        # app: cache.adapter.redis
        # default_redis_provider: redis://localhost:6379

        # Namespaced pools for different types of data
        pools:
            quiz.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600  # 1 hour
                
            quiz.short_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 300   # 5 minutes
                
            quiz.long_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400 # 24 hours

when@prod:
    framework:
        cache:
            # Use Redis in production if available
            # app: cache.adapter.redis
            # default_redis_provider: '%env(REDIS_URL)%'
            pools:
                quiz.cache:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 7200  # 2 hours in prod
                quiz.short_cache:
                    adapter: cache.adapter.filesystem  
                    default_lifetime: 600   # 10 minutes in prod
                quiz.long_cache:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 172800 # 48 hours in prod
